inventario/inventario/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import static
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
import inventarioComputo.views



urlpatterns = [
    
    path('', include('inventarioComputo.urls')),
    path('admin/', admin.site.urls),
    path('serviceworker.js', inventarioComputo.views.service_worker),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pwa.urls')),
    path('login/', 
        LoginView.as_view(
            template_name='registration/login.html'
        ), 
        name="login"
    ),
]

inventario/inventarioComputo/urls.py
from django.urls import path

from . import views 


app_name = 'inventarioComputo'

urlpatterns = [
    path('', views.index, name='index'),
    #re_path(r"^serviceworker\.js$", service_worker, name="serviceworker"),
    path('registro',views.registro,name='registro'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('listaProd',views.listaProd,name='listaProd'),
    path('cuenta', views.cuenta, name='cuenta'),
    path('crearProducto',views.crearProducto,name='crearProducto'),   
    path('edicionProducto/<int:producto_id>',views.edicionProducto),
    path('eliminarProducto/<int:producto_id>',views.eliminarProducto,name='eliminarProducto'),
    path('reporte', views.reporte, name='reporte'),
    path('prediccion', views.prediccion, name='prediccion'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('verCodigoBarras', views.verCodigoBarras, name='verCodigoBarras'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('verPdf', views.verPdf, name='verPdf'),
    path('cuenta', views.cuenta, name='cuenta'),
]

inventario/inventarioComputo/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import DecimalField, IntegerField, CharField
from django.db.models import Avg


class Producto(models.Model):
    cod_empresa = models.CharField(max_length=2)
    cod_producto = models.CharField(max_length=100)
    cod_proveedor = models.CharField(max_length=11, blank=True, null=True)
    cod_unidad_medida = models.CharField(max_length=3, blank=True, null=True)
    cod_tipo_producto = models.IntegerField()
    cod_garantia = models.CharField(max_length=3, blank=True, null=True)
    cod_linea_producto = models.CharField(max_length=5)
    cod_categoria = models.CharField(max_length=3, blank=True, null=True)
    cod_marca = models.CharField(max_length=5, blank=True, null=True)
    cod_presentacion = models.CharField(max_length=3, blank=True, null=True)
    cod_procedencia = models.CharField(max_length=3, blank=True, null=True)
    des_producto = models.CharField(max_length=255)
    des_adicional = models.TextField(blank=True, null=True)
    des_tecnicas = models.TextField(blank=True, null=True)
    des_info_adicional = models.TextField(blank=True, null=True)
    num_parte = models.CharField(max_length=50, blank=True, null=True)
    cod_barra = models.CharField(max_length=15, blank=True, null=True)
    fec_registro = models.DateField()
    stk_minimo = models.FloatField()
    stk_proveedor = models.FloatField()
    pre_costo_promedio_anterior = models.FloatField()
    pre_costo_promedio = models.FloatField()
    pre_compra_base = models.FloatField()
    pre_venta_base_anterior = models.FloatField()
    pre_venta_base = models.FloatField()
    pre_unitario_base_anterior = models.FloatField()
    pre_unitario_base = models.FloatField()
    pre_venta_oferta = models.FloatField()
    pre_unitario_oferta = models.FloatField()
    des_web_referencial = models.CharField(max_length=255)
    ind_servicio = models.CharField(max_length=1)
    ind_autogenerado = models.CharField(max_length=1)
    ind_lote_serie1 = models.CharField(max_length=1)
    ind_activo_web = models.CharField(max_length=1)
    ind_mostrar_portal = models.CharField(max_length=1)
    ind_catalogo = models.CharField(max_length=1)
    ind_lote = models.CharField(max_length=1)
    ind_importado = models.CharField(max_length=1)
    ind_activo = models.CharField(max_length=1)
    code_user_insert = models.CharField(max_length=10)
    date_insert = models.DateField(blank=True, null=True)
    code_user_last_update = models.CharField(max_length=10, blank=True, null=True)
    date_last_update = models.DateField(blank=True, null=True)
    ind_serie = models.CharField(max_length=1)

    def _str__(self):
        return self.name
    

class Colaborador(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    doc_ide = models.CharField(max_length=20,unique=True)
    correo = models.CharField(max_length=200,blank=True)
    telefono = models.CharField(max_length=20,blank=True)
    
    def __str__(self):
        return self.usuario.first_name

inventario/inventarioComputo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto

class UsuarioForm(forms.Form):
    usuario = forms.CharField(max_length=20,required=True)
    clave = forms.CharField(widget=forms.PasswordInput)

class ColaboradorForm(forms.Form):
    doc_ide = forms.CharField(label='DNI',max_length=20,required=True)
    nombres = forms.CharField(max_length=200,required=True)
    apellidos = forms.CharField(max_length=200,required=True)
    correo = forms.EmailField(required=True)
    telefono = forms.CharField(max_length=20,required=False)
    usuario = forms.CharField(max_length=20,required=True)
    clave = forms.CharField(widget=forms.PasswordInput)    
    
class ProductoForm(ModelForm):
    cod_empresa = forms.CharField(max_length=2,required=True)
    cod_producto= forms.CharField(max_length=100, required=True) 
    cod_proveedor = forms.CharField(max_length=11, required=False)
    cod_unidad_medida = forms.CharField(max_length=3, required=False)
    cod_tipo_producto = forms.IntegerField()
    cod_garantia = forms.CharField(max_length=3)
    cod_linea_producto = forms.CharField(max_length=5)
    cod_categoria = forms.CharField(max_length=3)
    cod_marca = forms.CharField(max_length=5)
    cod_presentacion = forms.CharField(max_length=3)
    cod_procedencia = forms.CharField(max_length=3)
    des_producto = forms.CharField(max_length=255)
    des_adicional = forms.CharField(widget=forms.Textarea)
    des_tecnicas = forms.CharField(widget=forms.Textarea)
    des_info_adicional = forms.CharField(widget=forms.Textarea)
    num_parte = forms.CharField(max_length=50)
    cod_barra = forms.CharField(max_length=15)
    fec_registro = forms.DateField()
    stk_minimo = forms.FloatField()
    stk_proveedor = forms.FloatField()
    pre_costo_promedio_anterior = forms.FloatField()
    pre_costo_promedio = forms.FloatField()
    pre_compra_base = forms.FloatField()
    pre_venta_base_anterior = forms.FloatField()
    pre_venta_base = forms.FloatField()
    pre_unitario_base_anterior = forms.FloatField()
    pre_unitario_base = forms.FloatField()
    pre_venta_oferta = forms.FloatField()
    pre_unitario_oferta = forms.FloatField()
    des_web_referencial = forms.CharField(max_length=255)
    ind_servicio = forms.CharField(max_length=1)
    ind_autogenerado = forms.CharField(max_length=1)
    ind_lote_serie1 = forms.CharField(max_length=1)
    ind_activo_web = forms.CharField(max_length=1)
    ind_mostrar_portal = forms.CharField(max_length=1)
    ind_catalogo = forms.CharField(max_length=1)
    ind_lote = forms.CharField(max_length=1)
    ind_importado = forms.CharField(max_length=1)
    ind_activo = forms.CharField(max_length=1)
    code_user_insert = forms.CharField(max_length=10)
    date_insert = forms.DateField()
    code_user_last_update = forms.CharField(max_length=10)
    date_last_update = forms.DateField()
    ind_serie = forms.CharField(max_length=1)
    class Meta:
       model = Producto
       fields = '__all__' 


    

      
    

inventario/inventarioComputo/views.py
from audioop import avg
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse
from flask import request

from .dashboard import get_piechart, get_plot1

from .utils import get_plot, get_prediction
from .models import Producto, Colaborador
from django.conf import settings
from django.views.generic.base import TemplateView
#IMPORTANDO METODOS PARA AUTENTICACIÓN DE USUARIOS
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.models import User
from inventarioComputo.forms import ColaboradorForm,UsuarioForm,ProductoForm
from django.contrib.auth.decorators import login_required
import pandas as pd 
from django.db.models import Avg
from django.db.models import Q
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
import cv2
from pyzbar.pyzbar import decode
from pydub import AudioSegment
from pydub.playback import play
# Import PDF Stuff
from django.http import FileResponse
from django.views.generic import View
import io
import reportlab
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter



# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    labels = []
    data = []
    labels1 = []
    data1 = []
    lista_productos = Producto.objects.all()
    lista_usuarios = User.objects.all()
    print(settings.MEDIA_URL)
    qs= Producto.objects.all()
    queryset= Producto.objects.order_by('-stk_minimo')[:5]
    queryset1= Producto.objects.order_by('-pre_venta_oferta')[:5]
    for producto in queryset:
        labels.append(producto.cod_producto)
        data.append(producto.stk_minimo)
        
    for producto in queryset1:
        labels1.append(producto.cod_producto)
        data1.append(producto.pre_venta_oferta)       
   # promedio_stock = qs.aggregate(Avg('stk_minimo'))
    total_stock = 0
    for item in qs:
        total_stock += item.stk_minimo
    x = [x.cod_producto for x in qs]
    y = [y.cod_categoria for y in qs]   
    tabla = get_plot1(x,y)  
    context = {'lstProductos': lista_productos,
               'tabla': tabla,
              # 'piechart': piechart,
               'total_stock': total_stock,
               'lista_usuarios': lista_usuarios,
               'labels': labels,
               'data': data,
               'labels1': labels1,
               'data1': data1,
               }
    
    return render(request,'index.html',context)


def listaProd(request):
    busqueda = request.POST.get("buscar")
    lista_productos = Producto.objects.all()
    print(settings.MEDIA_URL)
    
    if busqueda: 
        lista_productos = Producto.objects.filter(
           Q(id__icontains=busqueda) |
           Q(cod_producto__icontains= busqueda) |
           Q(des_producto__icontains= busqueda) |
           Q(cod_barra__icontains= busqueda)
        ).distinct() 
        
    context = {'lstProductos': lista_productos}
    return render(request,'listaProd.html',context)

def registro(request):
    frmColaborador = ColaboradorForm()
    
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        frmNuevoColaborador = ColaboradorForm(request.POST)
        # check whether it's valid:
        if frmColaborador.is_valid():
            data = frmNuevoColaborador.cleaned_data
            dataUsuario = data['usuario']
            dataPassword = data['clave']
            #creamos usuarios
            nuevoUsuario = User.objects.create_user(username=dataUsuario,password=dataPassword)
 
            nuevoUsuario.first_name = data['nombres']
            nuevoUsuario.last_name = data['apellidos']
            nuevoUsuario.email = data['correo']
            nuevoUsuario.save()       
            
            nuevoColaborador = Colaborador (usuario=nuevoUsuario)
            nuevoColaborador.telefono = data['telefono']
            nuevoColaborador.doc_ide = data['doc_ide']
            nuevoColaborador.save()
            
            return render(request,'graciasRegistro.html')
     
    context = {
         'frmColaborador': frmColaborador
     }     
    return render(request,'registroColaborador.html',context)  

def producto(request,producto_id):  
    objProducto = Producto.objects.get(id=producto_id) 
    #equivalente a : select * from producto where id = producto_id
    context = {
        "producto":objProducto
    }
    return render(request,'producto.html',context)

def crearProducto (request):
    if request.POST:
     frmProducto = ProductoForm(request.POST)
     
     if frmProducto.is_valid():
        frmProducto.save()
        messages.success(request, "Producto Registrado")
        return redirect('/listaProd')
     
    return render(request,'crearProducto.html',{'form':ProductoForm})

def edicionProducto(request,producto_id):
    producto = Producto.objects.get(id=producto_id) 
    form = ProductoForm(request.POST or None, instance = producto)
    if form.is_valid():
        form.save()
        messages.success(request, "Producto Registrado")
        return redirect('/listaProd')
    return render(request, "edicionProducto.html", {'producto': producto, 'form':form})    
 
 
def eliminarProducto(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
       
    
    if request.method == 'POST':
         objProducto.delete()  
         return redirect('/listaProd')

    context= {'item':objProducto}
    return render(request,'eliminarProducto.html',context) 

#metodos para visualizar los gráficos
def reporte(request):
    qs= Producto.objects.all()
    x = [x.cod_producto for x in qs]
    y = [y.stk_minimo for y in qs]   
    chart = get_plot(x,y) 
    return render(request, 'reporte.html', {'chart':chart})


def prediccion(request):
    qs= Producto.objects.all()
    x = [x.stk_minimo for x in qs]
    y = [y.stk_minimo for y in qs]   
    chart = get_prediction(x,y) 
    return render(request, 'prediccion.html', {'chart':chart})   

def dashboard(request):

    pass

def verCodigoBarras(request):
    video= cv2.VideoCapture(1)
    success, frame = video.read()
    detector = cv2.barcode.BarcodeDetector()
    
    while video.isOpened():
        while success:
            cv2.imshow('frame', frame)
            detectedBarcode = decode(frame)
            if cv2.waitKey(1) == ord('q'):
                break
            success, frame = video.read()
            if not detectedBarcode:
                print("No any Barcode Detected")
            else:
        # codes in barcode 
                for barcode in detectedBarcode:
                    # if barcode is not blank 
                    if barcode.data != "":
                        detectedBarcode = decode(frame)
                        cv2.putText(frame,str(barcode.data),(50,50),cv2.FONT_HERSHEY_COMPLEX,2,(0,255,255),2)
                        cv2.imwrite("barcode.png",frame)
                        
                                    
        text = str(barcode.data)
        video.release()
        cv2.destroyAllWindows()
        context = {
            "text" : text
        }
    
    return render(request, 'verCodigoBarras.html', context)

def nosotros (request):
    return render(request, 'nosotros.html')

def verPdf(request):
	# Create Bytestream buffer
        buf = io.BytesIO()
        # Create a canvas
        c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
        # Create a text object
        textob = c.beginText()
        textob.setTextOrigin(0.5*inch, 0.5*inch)
        textob.setFont("Helvetica", 8)

        # Add some lines of text
        #lines = [
        #	"This is line 1",
        #	"This is line 2",
        #	"This is line 3",
        #]
        
        # Designate The Model
        productos = Producto.objects.all()

        # Create blank list
        lines = []

        for producto in productos:
            lines.append(producto.des_producto)
            lines.append(str(producto.fec_registro))
            lines.append(str(producto.pre_venta_oferta))
            lines.append(" ")

        # Loop
        for line in lines:
            textob.textLine(line)

        # Finish Up
        c.drawText(textob)
        c.showPage()
        c.save()
        buf.seek(0)
            
        return FileResponse(buf, as_attachment=True, filename='productos.pdf')

def service_worker(request):
    sw_path = settings.BASE_DIR / "static/js/serviceworker.js" 
    response = HttpResponse(open(sw_path).read(), content_type='application/javascript')
    return response

def cuenta(request):
    return render(request, 'cuenta.html')

                
            
        

    




         

inventario/inventarioComputo/templates/chart.html
<div>
    <canvas id="myChart"></canvas>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <script>
    const ctx = document.getElementById('myChart');
  
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: {{labels|safe}},
        datasets: [{
          label: '# de productos en stock',
          data: {{data|safe}},
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
  

inventario/inventarioComputo/templates/cuenta.html
{% extends "layout.html" %}
{% block content %}
<div class="right_col" role="main">
    <img src="\static\img\logo.png" width="500" height="100"/>


    <h1>Bienvenido(a) : {{request.user.username}}</h1>

</div>
{% endblock %}

inventario/inventarioComputo/templates/dashboard.html
{% if tabla %}
<img src="data:image/png;base64, {{ tabla|safe}}">
{% endif %}

inventario/inventarioComputo/templates/eliminarProducto.html
{% extends "layout.html" %}
{% block content %}
<div class="right_col" role="main">
<p>Estás seguro que deseas eliminar "{{item}}"?</p>

<form action="{% url 'inventarioComputo:eliminarProducto' item.id %}" method="POST" >

    {% csrf_token %}
    <a href="{% url 'inventarioComputo:listaProd' %}"> Cancelar </a>

    <input type="submit" name="Confirmar">

</form>
</div>
{% endblock %}

inventario/inventarioComputo/templates/gestionProducto.html
{% extends "layout.html" %}
{% block content %}
<div class="container px-3 my-5 clearfix">
    <!-- Shopping cart table -->
    <div class="card">
        <div class="card-header">
            <h2>Gestionar Productos</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="min-width: 400px;">Producto</th>
                    <th class="text-right py-3 px-4" style="width: 100px;">Precio</th>
                    <th class="text-center py-3 px-4" style="width: 120px;">Cantidad</th>
                    <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                  </tr>
                </thead>
                <tbody>
                {% for key,value in request.session.cart.items %}
                  <tr>
                    <td class="p-4">
                      <div class="media align-items-center">
                        <div class="media-body">
                          <a href="{% url 'inventarioComputo:producto' value.id %}" class="d-block text-dark">{{ value.des_producto }}</a>
                        </div>
                      </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ value.pre_venta_oferta }}</td>
                    <td class="align-middle p-4"><input type="text" class="form-control text-center" value="{{ value.stk_minimo }}"></td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{ value.fec_registro }}</td>
                    <td class="text-center align-middle px-0"><a href="{% url 'inventarioComputo:eliminarProducto' value.id %}" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
                
            
          </div>
      </div>
  </div>
{% endblock %}

inventario/inventarioComputo/templates/graciasRegistro.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h2>Registro Exitoso</h2>
</div>
{% endblock %}

inventario/inventarioComputo/templates/layout.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="es">
    {% progressive_web_app_meta %} 
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="images/favicon.ico" type="image/ico" />

    <title>Inventario Computo Nacional</title>

    <!-- Bootstrap -->
    <link href="{% static '/style/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->


    <!-- Custom Theme Style -->
    <link href="{% static '/style/custom.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">  
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              
                <a href="/" class="site_title"></i> <span>Inventario Computo Nacional</span></a>
             </div>

            <div class="clearfix"></div>
            {% if request.user.is_authenticated%}
            <!-- menu profile quick info -->
            <div class="profile clearfix">
                <div class="profile_pic">
                <img src="static/img/main-logo.jpg" alt="..." class="img-circle profile_img">
                </div>
            <div class="profile_info">
              <span>Bienvenido,</span>
              <h2>{{request.user.username}}</h2>
            </div>
          </div>
          {% endif%}
          <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a aria-current="page" href="/"><i class="fa fa-home"></i> Inicio </span></a>
                    </li>                        
                    <li><a ><i class="fa fa-edit"></i> Gestionar producto <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{% url 'inventarioComputo:crearProducto' %}">Registrar Producto</a></li>
                            <li><a href="{% url 'inventarioComputo:verCodigoBarras' %}">Escanear Código</a></li> 
                            <li><a href="{% url 'inventarioComputo:listaProd' %}">Ver Productos</a></li>
                            
                          </ul>
                    </li>
                 <li><a href="{% url 'inventarioComputo:reporte' %}"><i class="fa fa-table"></i> Ver Reporte</span></a>
                    <li><a href="{% url 'inventarioComputo:nosotros' %}"><i class="fa fa-chevron-down"></i> Nosotros</span></a>
                    </li>                        
                </ul>
              </div>

                 
                 
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->
            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href={% url 'logout' %}>
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <nav class="nav navbar-nav">
              <ul class=" navbar-right">
                <li class="nav-item dropdown open" style="padding-left: 15px;">
                  
                    <a href="{{request.user.username}}" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false"> {{request.user.username}}
                    </a>
                        {% if not request.user.is_authenticated%}
                        
                        <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                        <a  class="dropdown-item" href="{% url 'login' %}" class="btn btn-primary"><i class="fa fa-sign-out pull-right"></i>Iniciar Sesión</a>
                        {% else %}  
                        <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item"  href="{% url 'inventarioComputo:cuenta' %}"> Perfil</a> 
                        <a href={% url 'logout' %}><i class="fa fa-sign-out pull-right"></i>Cerrar Sesión</a>
                        {% endif %}     
                    </div>
                  </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->



        <!-- ****************************************   -->

        {% block content %}
        {% endblock %}


        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Computo Nacional SAC 2023          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
 
    <!-- Custom Theme Scripts -->
    <script src="{% static '/js/custom.min.js' %}"></script>
	
  </body>
</html>

inventario/inventarioComputo/templates/listaProd.html
{% extends "layout.html" %}
{% block content %}

<div class="right_col" role="main">
    <h1>Lista de Productos</h1>
    {% block buscador %}

    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
    method="POST">
      {% csrf_token %}
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." name="buscar" value="{{ request.POST.buscar }}">
        <div class="input-group-append">
          <button type="submit">
            🔍
          </button>
          <th scope="col"><td><a class="btn btn-outline-dark mt-auto" href="{% url 'inventarioComputo:verPdf' %}">Exportar a PDF</a></td></th>
        </div>
      </div>
    </form>
    
    {% endblock buscador %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
            <table class="table border-secondary">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Descripción del producto</th>
                    <th scope="col">Código de Barras</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Cantidad</th>

                  </tr>
                </thead>
                
                <tbody>
                    {% for producto in lstProductos %}
                  <tr>
                    <th scope="row">{{ producto.id }}</th> 
                    <td>{{ producto.des_producto }}</td>
                    <td>{{ producto.cod_barra }}</td>
                    <td>S/. {{producto.pre_venta_oferta}}</td>
                    <td>{{producto.stk_minimo}}</td>
                    <td><a class="btn btn-outline-dark mt-auto" href="/edicionProducto/{{ producto.id }}">Editar</a></td>
                    <td><a class="btn btn-outline-dark mt-auto" href="{% url 'inventarioComputo:eliminarProducto' producto.id %}">Eliminar</a></td>
                  </tr>
                  {% endfor %}                  
                </tbody>
              
              </table>

</div>
{% endblock %}